#===============================================================================
										
BAPI_PRODORDCONF_CREATE_TT = {
		"returnThese": ['SAPReturn', 'output', 'sessionUUID', 'input'],
							  
		"bapi":"BAPI_PRODORDCONF_CREATE_TT",
							 
		"parameterValues":{'input' : 
							 {'inputRoot' : 
							  {'TABLES' : 
								{'TIMETICKETS' : 
								  {'item' : [
									{'CONF_NO' : '',
									'ORDERID' : '',
									'SEQUENCE' : '',
									'OPERATION' : '',
									'SUB_OPER' : '',
									'CAPA_CATEGORY' : '',
									'SPLIT' : '',
									'FIN_CONF' : '',
									'CLEAR_RES' : '',
									'POSTG_DATE' : '',
									'DEV_REASON' : '',
									'CONF_TEXT' : '',
									'PLANT' : '',
									'WORK_CNTR' : '',
									'RECORDTYPE' : '',
									'CONF_QUAN_UNIT' : '',
									'CONF_QUAN_UNIT_ISO' : '',
									'YIELD' : '',
									'SCRAP' : '',
									'REWORK' : '',
									'CONF_ACTI_UNIT1' : '',
									'CONF_ACTI_UNIT1_ISO' : '',
									'CONF_ACTIVITY1' : '',
									'NO_REMN_ACTI1' : '',
									'CONF_ACTI_UNIT2' : '',
									'CONF_ACTI_UNIT2_ISO' : '',
									'CONF_ACTIVITY2' : '',
									'NO_REMN_ACTI2' : '',
									'CONF_ACTI_UNIT3' : '',
									'CONF_ACTI_UNIT3_ISO' : '',
									'CONF_ACTIVITY3' : '',
									'NO_REMN_ACTI3' : '',
									'CONF_ACTI_UNIT4' : '',
									'CONF_ACTI_UNIT4_ISO' : '',
									'CONF_ACTIVITY4' : '',
									'NO_REMN_ACTI4' : '',
									'CONF_ACTI_UNIT5' : '',
									'CONF_ACTI_UNIT5_ISO' : '',
									'CONF_ACTIVITY5' : '',
									'NO_REMN_ACTI5' : '',
									'CONF_ACTI_UNIT6' : '',
									'CONF_ACTI_UNIT6_ISO' : '',
									'CONF_ACTIVITY6' : '',
									'NO_REMN_ACTI6' : '',
									'CONF_BUS_PROC_UNIT1' : '',
									'CONF_BUS_PROC_UNIT1_ISO' : '',
									'CONF_BUS_PROC1' : '',
									'NO_REMN_BUS_PROC1' : '',
									'EXEC_START_DATE' : '',
									'EXEC_START_TIME' : '',
									'SETUP_FIN_DATE' : '',
									'SETUP_FIN_TIME' : '',
									'PROC_START_DATE' : '',
									'PROC_START_TIME' : '',
									'PROC_FIN_DATE' : '',
									'PROC_FIN_TIME' : '',
									'TEARDOWN_START_DATE' : '',
									'TEARDOWN_START_TIME' : '',
									'EXEC_FIN_DATE' : '',
									'EXEC_FIN_TIME' : '',
									'FCST_FIN_DATE' : '',
									'FCST_FIN_TIME' : '',
									'STD_UNIT1' : '',
									'STD_UNIT1_ISO' : '',
									'FORCAST_STD_VAL1' : '',
									'STD_UNIT2' : '',
									'STD_UNIT2_ISO' : '',
									'FORCAST_STD_VAL2' : '',
									'STD_UNIT3' : '',
									'STD_UNIT3_ISO' : '',
									'FORCAST_STD_VAL3' : '',
									'STD_UNIT4' : '',
									'STD_UNIT4_ISO' : '',
									'FORCAST_STD_VAL4' : '',
									'STD_UNIT5' : '',
									'STD_UNIT5_ISO' : '',
									'FORCAST_STD_VAL5' : '',
									'STD_UNIT6' : '',
									'STD_UNIT6_ISO' : '',
									'FORCAST_STD_VAL6' : '',
									'FORCAST_BUS_PROC_UNIT1' : '',
									'FORC_BUS_PROC_UNIT1_ISO' : '',
									'FORCAST_BUS_PROC_VAL1' : '',
									'PERS_NO' : '',
									'TIMEID_NO' : '',
									'WAGETYPE' : '',
									'SUITABILITY' : '',
									'NO_OF_EMPLOYEE' : '',
									'WAGEGROUP' : '',
									'BREAK_UNIT' : '',
									'BREAK_UNIT_ISO' : '',
									'BREAK_TIME' : '',
									'EX_CREATED_BY' : '',
									'EX_CREATED_DATE' : '',
									'EX_CREATED_TIME' : '',
									'TARGET_ACTI1' : '',
									'TARGET_ACTI2' : '',
									'TARGET_ACTI3' : '',
									'TARGET_ACTI4' : '',
									'TARGET_ACTI5' : '',
									'TARGET_ACTI6' : '',
									'TARGET_BUS_PROC1' : '',
									'EX_IDENT' : '',
									'LOGDATE' : '',
									'LOGTIME' : '',
									'WIP_BATCH' : '',
									'VENDRBATCH' : '',
									'ME_SFC_ID' : '',
									'ME_2ND_CONF_QTY' : ''}]},
								"LINK_CONF_GOODSMOV": 
								{"item": [{
								   "INDEX_CONFIRM": "",
								   "INDEX_GM_DEPEND": "",
								   "INDEX_GOODSMOV": ""
								}]},
								'GOODSMOVEMENTS' : 
								  {'item' : [
									{'MATERIAL' : '',
									'PLANT' : '',
									'STGE_LOC' : '',
									'BATCH' : '',
									'MOVE_TYPE' : '',
									'STCK_TYPE' : '',
									'SPEC_STOCK' : '',
									'VENDOR' : '',
									'CUSTOMER' : '',
									'SALES_ORD' : '',
									'S_ORD_ITEM' : '',
									'SCHED_LINE' : '',
									'VAL_TYPE' : '',
									'ENTRY_QNT' : '',
									'ENTRY_UOM' : '',
									'ENTRY_UOM_ISO' : '',
									'PO_PR_QNT' : '',
									'ORDERPR_UN' : '',
									'ORDERPR_UN_ISO' : '',
									'PO_NUMBER' : '',
									'PO_ITEM' : '',
									'SHIPPING' : '',
									'COMP_SHIP' : '',
									'NO_MORE_GR' : '',
									'ITEM_TEXT' : '',
									'GR_RCPT' : '',
									'UNLOAD_PT' : '',
									'COSTCENTER' : '',
									'ORDERID' : '',
									'ORDER_ITNO' : '',
									'CALC_MOTIVE' : '',
									'ASSET_NO' : '',
									'SUB_NUMBER' : '',
									'RESERV_NO' : '',
									'RES_ITEM' : '',
									'RES_TYPE' : '',
									'WITHDRAWN' : '',
									'MOVE_MAT' : '',
									'MOVE_PLANT' : '',
									'MOVE_STLOC' : '',
									'MOVE_BATCH' : '',
									'MOVE_VAL_TYPE' : '',
									'MVT_IND' : '',
									'MOVE_REAS' : '',
									'RL_EST_KEY' : '',
									'REF_DATE' : '',
									'COST_OBJ' : '',
									'PROFIT_SEGM_NO' : '',
									'PROFIT_CTR' : '',
									'WBS_ELEM' : '',
									'NETWORK' : '',
									'ACTIVITY' : '',
									'PART_ACCT' : '',
									'AMOUNT_LC' : '',
									'AMOUNT_SV' : '',
									'REF_DOC_YR' : '',
									'REF_DOC' : '',
									'REF_DOC_IT' : '',
									'EXPIRYDATE' : '',
									'PROD_DATE' : '',
									'FUND' : '',
									'FUNDS_CTR' : '',
									'CMMT_ITEM' : '',
									'VAL_SALES_ORD' : '',
									'VAL_S_ORD_ITEM' : '',
									'VAL_WBS_ELEM' : '',
									'GL_ACCOUNT' : '',
									'IND_PROPOSE_QUANX' : '',
									'XSTOB' : '',
									'EAN_UPC' : '',
									'DELIV_NUMB_TO_SEARCH' : '',
									'DELIV_ITEM_TO_SEARCH' : '',
									'SERIALNO_AUTO_NUMBERASSIGNMENT' : '',
									'VENDRBATCH' : '',
									'STGE_TYPE' : '',
									'STGE_BIN' : '',
									'SU_PL_STCK_1' : '',
									'ST_UN_QTYY_1' : '',
									'ST_UN_QTYY_1_ISO' : '',
									'UNITTYPE_1' : '',
									'SU_PL_STCK_2' : '',
									'ST_UN_QTYY_2' : '',
									'ST_UN_QTYY_2_ISO' : '',
									'UNITTYPE_2' : '',
									'STGE_TYPE_PC' : '',
									'STGE_BIN_PC' : '',
									'NO_PST_CHGNT' : '',
									'GR_NUMBER' : '',
									'STGE_TYPE_ST' : '',
									'STGE_BIN_ST' : '',
									'MATDOC_TR_CANCEL' : '',
									'MATITEM_TR_CANCEL' : '',
									'MATYEAR_TR_CANCEL' : '',
									'NO_TRANSFER_REQ' : '',
									'CO_BUSPROC' : '',
									'ACTTYPE' : '',
									'SUPPL_VEND' : '',
									'MATERIAL_EXTERNAL' : '',
									'MATERIAL_GUID' : '',
									'MATERIAL_VERSION' : '',
									'MOVE_MAT_EXTERNAL' : '',
									'MOVE_MAT_GUID' : '',
									'MOVE_MAT_VERSION' : '',
									'FUNC_AREA' : '',
									'TR_PART_BA' : '',
									'PAR_COMPCO' : '',
									'DELIV_NUMB' : '',
									'DELIV_ITEM' : '',
									'NB_SLIPS' : '',
									'NB_SLIPSX' : '',
									'GR_RCPTX' : '',
									'UNLOAD_PTX' : '',
									'SPEC_MVMT' : '',
									'GRANT_NBR' : '',
									'CMMT_ITEM_LONG' : '',
									'FUNC_AREA_LONG' : '',
									'LINE_ID' : '',
									'PARENT_ID' : '',
									'LINE_DEPTH' : '',
									'QUANTITY' : '',
									'BASE_UOM' : '',
									'LONGNUM' : '',
									'BUDGET_PERIOD' : '',
									'EARMARKED_NUMBER' : '',
									'EARMARKED_ITEM' : '',
									'STK_SEGMENT' : '',
									'MOVE_SEGMENT' : '',
									'MATERIAL_LONG' : '',
									'MOVE_MAT_LONG' : '',
									'EXT_BASE_AMOUNT' : '',
									'TAX_CODE' : ''}]}},
							  'INPUT' : 
								{'CALL_ON_INBOUND_QUEUE' : '',
								'POST_WRONG_ENTRIES' : '',
								'TESTRUN' : ''}}}}
}

										
#===============================================================================

BAPI_GOODSMVT_CREATE = {
		"returnThese": ['SAPReturn', 'input', "output"],
		
		"bapi": "BAPI_GOODSMVT_CREATE",
					  
		"parameterValues":{"input": {'inputRoot' : 
										  {'INPUT' : 
											{'TESTRUN' : '',
											'GOODSMVT_CODE' : 
											  {'GM_CODE' : ''},
											'GOODSMVT_HEADER' : 
											  {'PSTNG_DATE' : '',
											  'DOC_DATE' : '',
											  'REF_DOC_NO' : '',
											  'BILL_OF_LADING' : '',
											  'GR_GI_SLIP_NO' : '',
											  'PR_UNAME' : '',
											  'HEADER_TXT' : '',
											  'VER_GR_GI_SLIP' : '',
											  'VER_GR_GI_SLIPX' : '',
											  'EXT_WMS' : '',
											  'REF_DOC_NO_LONG' : '',
											  'BILL_OF_LADING_LONG' : '',
											  'BAR_CODE' : ''},
											'GOODSMVT_REF_EWM' : 
											  {'REF_DOC_EWM' : '',
											  'LOGSYS' : '',
											  'GTS_SCRAP_NO' : ''}},
										  'TABLES' : 
											{'GOODSMVT_ITEM' : 
											  {'item' : [
												{'MATERIAL' : '',
												'PLANT' : '',
												'STGE_LOC' : '',
												'BATCH' : '',
												'MOVE_TYPE' : '',
												'STCK_TYPE' : '',
												'SPEC_STOCK' : '',
												'VENDOR' : '',
												'CUSTOMER' : '',
												'SALES_ORD' : '',
												'S_ORD_ITEM' : '',
												'SCHED_LINE' : '',
												'VAL_TYPE' : '',
												'ENTRY_QNT' : '',
												'ENTRY_UOM' : '',
												'ENTRY_UOM_ISO' : '',
												'PO_PR_QNT' : '',
												'ORDERPR_UN' : '',
												'ORDERPR_UN_ISO' : '',
												'PO_NUMBER' : '',
												'PO_ITEM' : '',
												'SHIPPING' : '',
												'COMP_SHIP' : '',
												'NO_MORE_GR' : '',
												'ITEM_TEXT' : '',
												'GR_RCPT' : '',
												'UNLOAD_PT' : '',
												'COSTCENTER' : '',
												'ORDERID' : '',
												'ORDER_ITNO' : '',
												'CALC_MOTIVE' : '',
												'ASSET_NO' : '',
												'SUB_NUMBER' : '',
												'RESERV_NO' : '',
												'RES_ITEM' : '',
												'RES_TYPE' : '',
												'WITHDRAWN' : '',
												'MOVE_MAT' : '',
												'MOVE_PLANT' : '',
												'MOVE_STLOC' : '',
												'MOVE_BATCH' : '',
												'MOVE_VAL_TYPE' : '',
												'MVT_IND' : '',
												'MOVE_REAS' : '',
												'RL_EST_KEY' : '',
												'REF_DATE' : '',
												'COST_OBJ' : '',
												'PROFIT_SEGM_NO' : '',
												'PROFIT_CTR' : '',
												'WBS_ELEM' : '',
												'NETWORK' : '',
												'ACTIVITY' : '',
												'PART_ACCT' : '',
												'AMOUNT_LC' : '',
												'AMOUNT_SV' : '',
												'REF_DOC_YR' : '',
												'REF_DOC' : '',
												'REF_DOC_IT' : '',
												'EXPIRYDATE' : '',
												'PROD_DATE' : '',
												'FUND' : '',
												'FUNDS_CTR' : '',
												'CMMT_ITEM' : '',
												'VAL_SALES_ORD' : '',
												'VAL_S_ORD_ITEM' : '',
												'VAL_WBS_ELEM' : '',
												'GL_ACCOUNT' : '',
												'IND_PROPOSE_QUANX' : '',
												'XSTOB' : '',
												'EAN_UPC' : '',
												'DELIV_NUMB_TO_SEARCH' : '',
												'DELIV_ITEM_TO_SEARCH' : '',
												'SERIALNO_AUTO_NUMBERASSIGNMENT' : '',
												'VENDRBATCH' : '',
												'STGE_TYPE' : '',
												'STGE_BIN' : '',
												'SU_PL_STCK_1' : '',
												'ST_UN_QTYY_1' : '',
												'ST_UN_QTYY_1_ISO' : '',
												'UNITTYPE_1' : '',
												'SU_PL_STCK_2' : '',
												'ST_UN_QTYY_2' : '',
												'ST_UN_QTYY_2_ISO' : '',
												'UNITTYPE_2' : '',
												'STGE_TYPE_PC' : '',
												'STGE_BIN_PC' : '',
												'NO_PST_CHGNT' : '',
												'GR_NUMBER' : '',
												'STGE_TYPE_ST' : '',
												'STGE_BIN_ST' : '',
												'MATDOC_TR_CANCEL' : '',
												'MATITEM_TR_CANCEL' : '',
												'MATYEAR_TR_CANCEL' : '',
												'NO_TRANSFER_REQ' : '',
												'CO_BUSPROC' : '',
												'ACTTYPE' : '',
												'SUPPL_VEND' : '',
												'MATERIAL_EXTERNAL' : '',
												'MATERIAL_GUID' : '',
												'MATERIAL_VERSION' : '',
												'MOVE_MAT_EXTERNAL' : '',
												'MOVE_MAT_GUID' : '',
												'MOVE_MAT_VERSION' : '',
												'FUNC_AREA' : '',
												'TR_PART_BA' : '',
												'PAR_COMPCO' : '',
												'DELIV_NUMB' : '',
												'DELIV_ITEM' : '',
												'NB_SLIPS' : '',
												'NB_SLIPSX' : '',
												'GR_RCPTX' : '',
												'UNLOAD_PTX' : '',
												'SPEC_MVMT' : '',
												'GRANT_NBR' : '',
												'CMMT_ITEM_LONG' : '',
												'FUNC_AREA_LONG' : '',
												'LINE_ID' : '',
												'PARENT_ID' : '',
												'LINE_DEPTH' : '',
												'QUANTITY' : '',
												'BASE_UOM' : '',
												'LONGNUM' : '',
												'BUDGET_PERIOD' : '',
												'EARMARKED_NUMBER' : '',
												'EARMARKED_ITEM' : '',
												'STK_SEGMENT' : '',
												'MOVE_SEGMENT' : '',
												'MATERIAL_LONG' : '',
												'MOVE_MAT_LONG' : '',
												'EXT_BASE_AMOUNT' : '',
												'TAX_CODE' : ''}]},
											'GOODSMVT_SERIALNUMBER' : 
											  {'item' : [
												{'MATDOC_ITM' : '',
												'SERIALNO' : '',
												'UII' : ''}]},
											'GOODSMVT_SERV_PART_DATA' : 
											  {'item' : [
												{'LINE_ID' : '',
												'RET_AUTH_NUMBER' : '',
												'DELIV_NUMBER' : '',
												'DELIV_ITEM' : '',
												'HU_NUMBER' : '',
												'INSPOUT_GUID' : '',
												'EVENT' : '',
												'DATE' : '',
												'TIME' : '',
												'ZONLO' : '',
												'TIMESTAMP' : '',
												'SCRAP_INDICATOR' : '',
												'KEEP_QUANTITY' : '',
												'GTS_STOCK_TYPE' : '',
												'MOVE_GTS_STOCK_TYPE' : '',
												'KEEP_QUANTITY_CONVERSION' : '',
												'ZERO_QUANTITY' : '',
												'NUMERATOR' : '',
												'DENOMINATR' : '',
												'INSP_DOC_NUMB' : '',
												'PCHG_TYPE' : ''}]}}}}}}
					  

#===============================================================================												  

BAPI_TRANSACTION_COMMIT = {
		"returnThese": ['SAPReturn', 'output'],

		"bapi": "BAPI_TRANSACTION_COMMIT",

		"parameterValues": {}}

#===============================================================================

BAPI_TRANSACTION_ROLLBACK = {
		"returnThese": ['SAPReturn', 'output'],
		
		"bapi": "BAPI_TRANSACTION_ROLLBACK",

		"parameterValues": {}}
		
#===============================================================================

BAPI_PRODORDCONF_GETDETAIL = {
		"returnThese" : ['SAPReturn','input', 'output'],

		"bapi" : "BAPI_PRODORDCONF_GETDETAIL",
		
		"parameterValues" : 
					{ 	
					'input' : 
					 {'inputRoot' : 
					  {'INPUT' : 
					    {'CONFIRMATION' : '0317653757',
					    'CONFIRMATIONCOUNTER' : '00000036'}}}
                    	
                    }
		}
		

#==============================================================================

BAPI_PRODORDCONF_GETLIST = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PRODORDCONF_GETLIST",
				
				"parameterValues" : 
							{ 	
							'input' : 
							 {'inputRoot' : 
							  {'orderRange' : 
							    {'sign' : 'I',
							    'option' : 'EQ',
							    'low' : '000000000000',
							    'high' : ''}}}
								
							}
					}

#============================================================================

BAPI_PRODORD_GET_DETAIL = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PRODORD_GET_DETAIL",
				
				"parameterValues" : 
							{ 	
							'input' : 
							 {'inputRoot' : 
							  {'INPUT' : 
							    {'NUMBER' : '',
							    'ORDER_OBJECTS' : 
							      {'HEADER' : '',
							      'OPERATIONS' : '',
							      'POSITIONS' : '',
							      'SEQUENCES' : '',
							      'COMPONENTS' : '',
							      'PRO_REL_TOOLS' : '',
							      'TRIGGER_POINTS' : '',
							      'SUBOPERATIONS' : ''},
							    'COLLECTIVE_ORDER' : ''}}}				
							}
					}
					
				
#===========================================================================

BAPI_PRODORDCONF_CANCEL = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PRODORDCONF_CANCEL",
				
				"parameterValues" : 
							{'input' : 
							 {'inputRoot' : 
							  {'INPUT' : 
								{'CONFIRMATION' : '',
								'CONFIRMATIONCOUNTER' : ''}
							}}}
				}
				
#===========================================================================

BAPI_PRODORDCONF_CREATE_HDR = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PRODORDCONF_CREATE_HDR",
				
				"parameterValues" : 
							{'input' : 
							 {'inputRoot' : 
							  {'TABLES' : 
								{'ATHDRLEVELS' : 
								  {'item' : [
									{'ORDERID' : '',
									'FIN_CONF' : '',
									'CLEAR_RES' : '',
									'POSTG_DATE' : '',
									'DEV_REASON' : '',
									'CONF_TEXT' : '',
									'EX_CREATED_BY' : '',
									'EX_CREATED_DATE' : '',
									'EX_CREATED_TIME' : '',
									'CONF_QUAN_UNIT' : '',
									'CONF_QUAN_UNIT_ISO' : '',
									'YIELD' : '',
									'SCRAP' : '',
									'REWORK' : '',
									'EXEC_START_DATE' : '',
									'EXEC_START_TIME' : '',
									'EXEC_FIN_DATE' : '',
									'EXEC_FIN_TIME' : '',
									'PERS_NO' : '',
									'EX_IDENT' : ''}]}}}}}
				}


#===========================================================================

BAPI_PRODORDCONF_CREATE_TE = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PRODORDCONF_CREATE_TE",
				
				"parameterValues" : {'input' : 
						 {'inputRoot' : 
						  {'TABLES' : 
							{'TIMEEVENTS' : 
							  {'item' : [
								{'CONF_NO' : '',
								'ORDERID' : '',
								'SEQUENCE' : '',
								'OPERATION' : '',
								'SUB_OPER' : '',
								'CAPA_CATEGORY' : '',
								'SPLIT' : '',
								'RECORDTYPE' : '',
								'LOGDATE' : '',
								'LOGTIME' : '',
								'FIN_CONF' : '',
								'CLEAR_RES' : '',
								'POSTG_DATE' : '',
								'DEV_REASON' : '',
								'CONF_TEXT' : '',
								'CONF_QUAN_UNIT' : '',
								'CONF_QUAN_UNIT_ISO' : '',
								'YIELD' : '',
								'SCRAP' : '',
								'REWORK' : '',
								'PLANT' : '',
								'WORK_CNTR' : '',
								'CONF_ACTI_UNIT1' : '',
								'CONF_ACTI_UNIT1_ISO' : '',
								'CONF_ACTIVITY1' : '',
								'NO_REMN_ACTI1' : '',
								'CONF_ACTI_UNIT2' : '',
								'CONF_ACTI_UNIT2_ISO' : '',
								'CONF_ACTIVITY2' : '',
								'NO_REMN_ACTI2' : '',
								'CONF_ACTI_UNIT3' : '',
								'CONF_ACTI_UNIT3_ISO' : '',
								'CONF_ACTIVITY3' : '',
								'NO_REMN_ACTI3' : '',
								'CONF_ACTI_UNIT4' : '',
								'CONF_ACTI_UNIT4_ISO' : '',
								'CONF_ACTIVITY4' : '',
								'NO_REMN_ACTI4' : '',
								'CONF_ACTI_UNIT5' : '',
								'CONF_ACTI_UNIT5_ISO' : '',
								'CONF_ACTIVITY5' : '',
								'NO_REMN_ACTI5' : '',
								'CONF_ACTI_UNIT6' : '',
								'CONF_ACTI_UNIT6_ISO' : '',
								'CONF_ACTIVITY6' : '',
								'NO_REMN_ACTI6' : '',
								'CONF_BUS_PROC_UNIT1' : '',
								'CONF_BUS_PROC_UNIT1_ISO' : '',
								'CONF_BUSS_PROC1' : '',
								'NO_REMN_BUS_PROC1' : '',
								'PERS_NO' : '',
								'TIMEID_NO' : '',
								'WAGETYPE' : '',
								'EX_CREATED_BY' : '',
								'EX_CREATED_DATE' : '',
								'EX_CREATED_TIME' : '',
								'TARGET_ACTI1' : '',
								'TARGET_ACTI2' : '',
								'TARGET_ACTI3' : '',
								'TARGET_ACTI4' : '',
								'TARGET_ACTI5' : '',
								'TARGET_ACTI6' : '',
								'TARGET_BUS_PROC1' : '',
								'EX_IDENT' : ''}]}}}}}
}

#===========================================================================


BAPI_PRODORDCONF_CREATE_ACT = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PRODORDCONF_CREATE_ACT",
				
				"parameterValues" : {
						'input' : 
						 {'inputRoot' : 
						  {'TABLES' : 
							{'ACTIVITIES' : 
							  {'item' : [
								{'CONF_NO' : '',
								'ORDERID' : '',
								'SEQUENCE' : '',
								'OPERATION' : '',
								'SUB_OPER' : '',
								'CAPA_CATEGORY' : '',
								'SPLIT' : '',
								'LOG_SYSTEM' : '',
								'PERS_NO' : '',
								'TIMEID_NO' : '',
								'WORK_CNTR' : '',
								'PLANT' : '',
								'LOGDATE' : '',
								'LOGTIME' : '',
								'POSTG_DATE' : '',
								'DEV_REASON' : '',
								'CONF_TEXT' : '',
								'SETUP_VAL' : '',
								'SETUP_UNIT' : '',
								'SETUP_UNITISO' : '',
								'MACHI_VAL' : '',
								'MACHI_UNIT' : '',
								'MACHI_UNITISO' : '',
								'LABOR_VAL' : '',
								'LABOR_UNIT' : '',
								'LABOR_UNITISO' : '',
								'TEARD_VAL' : '',
								'TEARD_UNIT' : '',
								'TAERD_UNITISO' : '',
								'VACT1_VAL' : '',
								'VACT1_UNIT' : '',
								'VACT1_UNITISO' : '',
								'WAGETYPE' : '',
								'EX_CREATED_BY' : '',
								'EX_CREATED_DATE' : '',
								'EX_CREATED_TIME' : '',
								'EX_IDENT' : ''}]}}}}
				}
}

#===========================================================================


BAPI_GOODSMVT_GETITEMS = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_GOODSMVT_GETITEMS",
				
				"parameterValues" : {
							'input' : 
							 {'inputRoot' : 
							  {'TABLES' : 
								{'BATCH_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'MATERIAL_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : '',
									'HIGH_EXTERNAL' : '',
									'HIGH_GUID' : '',
									'HIGH_VERSION' : '',
									'LOW_EXTERNAL' : '',
									'LOW_GUID' : '',
									'LOW_VERSION' : '',
									'LOW_LONG' : '',
									'HIGH_LONG' : ''}]},
								'MOVE_TYPE_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'PLANT_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'PSTNG_DATE_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'PURCH_DOC_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'SPEC_STOCK_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'STGE_LOC_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'TR_EV_TYPE_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'USERNAME_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]},
								'VENDOR_RA' : 
								  {'item' : [
									{'SIGN' : '',
									'OPTION' : '',
									'LOW' : '',
									'HIGH' : ''}]}}}}
									}
}

#===========================================================================

BAPI_MATERIAL_GET_DETAIL = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_MATERIAL_GET_DETAIL",
				
				"parameterValues": { 'input': 
									 {'inputRoot' : 
									  {'INPUT' : 
										{'MATERIAL' : '',
										'MATERIAL_LONG' : '',
										'PLANT' : '',
										'VALUATIONAREA' : '',
										'VALUATIONTYPE' : '',
										'MATERIAL_EVG' : 
										  {'MATERIAL_EXT' : '',
										  'MATERIAL_VERS' : '',
										  'MATERIAL_GUID' : ''}}}}
				}

}

#===========================================================================

BAPI_MATERIAL_GETLIST = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_MATERIAL_GETLIST",
				
				"parameterValues": { 'input' : 
								 {'inputRoot' : 
								  {'INPUT' : 
									{'MAXROWS' : ''},
								  'TABLES' : 
									{'DISTRIBUTIONCHANNELSELECTION' : 
									  {'item' : [
										{'SIGN' : '',
										'OPTION' : '',
										'DISTR_CHAN_LOW' : '',
										'DISTR_CHAN_HIGH' : ''}]},
									'MANUFACTURERPARTNUMB' : 
									  {'item' : [
										{'MANU_MAT' : '',
										'MFR_NO' : ''}]},
									'MATERIALSHORTDESCSEL' : 
									  {'item' : [
										{'SIGN' : '',
										'OPTION' : '',
										'DESCR_LOW' : '',
										'DESCR_HIGH' : ''}]},
									'MATNRLIST' : 
									  {'item' : [
										{'MATERIAL' : '',
										'MATL_DESC' : '',
										'MATERIAL_EXTERNAL' : '',
										'MATERIAL_GUID' : '',
										'MATERIAL_VERSION' : '',
										'MATERIAL_LONG' : ''}]},
									'MATNRSELECTION' : 
									  {'item' : [
										{'SIGN' : '',
										'OPTION' : '',
										'MATNR_LOW' : '',
										'MATNR_HIGH' : '',
										'MATNR_HIGH_EXTERNAL' : '',
										'MATNR_HIGH_GUID' : '',
										'MATNR_HIGH_VERSION' : '',
										'MATNR_LOW_EXTERNAL' : '',
										'MATNR_LOW_GUID' : '',
										'MATNR_LOW_VERSION' : '',
										'MATNR_LOW_LONG' : '',
										'MATNR_HIGH_LONG' : ''}]},
									'PLANTSELECTION' : 
									  {'item' : [
										{'SIGN' : '',
										'OPTION' : '',
										'PLANT_LOW' : '',
										'PLANT_HIGH' : ''}]},
									'SALESORGANISATIONSELECTION' : 
									  {'item' : [
										{'SIGN' : '',
										'OPTION' : '',
										'SALESORG_LOW' : '',
										'SALESORG_HIGH' : ''}]},
									'STORAGELOCATIONSELECT' : 
									  {'item' : [
										{'SIGN' : '',
										'OPTION' : '',
										'STLOC_LOW' : '',
										'STLOC_HIGH' : ''}]}}}}
				}
}

#=============================================================================

BAPI_PROCORDCONF_EXIST_CHK = {
	
				"returnThese" : ['input', 'SAPReturn'],
		
				"bapi" : "BAPI_PROCORDCONF_EXIST_CHK",
				
				"parameterValues" : 
							{'input' : 
							 {'inputRoot' : 
							  {'INPUT' : 
								{'CONFIRMATION' : '',
								'CONFIRMATIONCOUNTER' : ''}
							}}}
				
}

#=============================================================================

BAPI_MATERIAL_DISPLAY = {
				"returnThese" : ['input', 'SAPReturn'],
		
				"bapi" : "BAPI_MATERIAL_DISPLAY",
				
				"parameterValues" : {
							'input' : 
								 {'inputRoot' : 
								  {'INPUT' : 
									{'MATERIAL' : '',
									'MATERIAL_LONG' : '',
									'MATERIAL_EVG' : 
									  {'MATERIAL_EXT' : '',
									  'MATERIAL_VERS' : '',
									  'MATERIAL_GUID' : ''}}}}}
									  
									  
}

BAPI_GOODSMVT_GETDETAIL = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_GOODSMVT_GETDETAIL",
				
				"parameterValues" : {
							'input' : 
								 {'inputRoot' : 
								  {'INPUT' : 
									{'MATDOCUMENTYEAR' : '',
									'MATERIALDOCUMENT' : ''}}}}
}


ZPP_IGN_PROCORDCONF_CREATE_TT = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
				
				"bapi" : "ZPP_IGN_PROCORDCONF_CREATE_TT",
				
				"parameterValues": {
							'input' : 
								 {'inputRoot' : 
								  {'INPUT' : 
									{'CALL_ON_INBOUND_QUEUE' : '',
									'POST_WRONG_ENTRIES' : '',
									'TESTRUN' : ''},
								  'TABLES' : 
									{'IT_GOODSMOVEMENTS' : 
									  {'item' : [
										{'ZID' : '',
										'ZSEQNO' : '',
										'MATERIAL' : '',
										'PLANT' : '',
										'STGE_LOC' : '',
										'BATCH' : '',
										'MOVE_TYPE' : '',
										'ENTRY_QNT' : '',
										'ENTRY_UOM' : '',
										'PROD_DATE' : '',
										'STCK_TYPE' : ''}]},
									'IT_TIMETICKETS' : 
									  {'item' : [
										{'ZID' : '',
										'CONF_NO' : '',
										'ORDERID' : '',
										'OPERATION' : '',
										'FIN_CONF' : '',
										'CLEAR_RES' : '',
										'POSTG_DATE' : '',
										'PLANT' : '',
										'WORK_CNTR' : '',
										'CONF_QUAN_UNIT' : '',
										'YIELD' : '',
										'SCRAP' : '',
										'REWORK' : '',
										'DEV_REASON' : '',
										'PERS_NO' : '',
										'EXEC_START_DATE' : '',
										'EXEC_START_TIME' : '',
										'EXEC_FIN_DATE' : '',
										'EXEC_FIN_TIME' : '',
										'CONF_ACTI_UNIT1' : '',
										'CONF_ACTI_UNIT1_ISO' : '',
										'CONF_ACTIVITY1' : '',
										'NO_REMN_ACTI1' : '',
										'CONF_ACTI_UNIT2' : '',
										'CONF_ACTI_UNIT2_ISO' : '',
										'CONF_ACTIVITY2' : '',
										'NO_REMN_ACTI2' : '',
										'CONF_ACTI_UNIT3' : '',
										'CONF_ACTI_UNIT3_ISO' : '',
										'CONF_ACTIVITY3' : '',
										'NO_REMN_ACTI3' : '',
										'CONF_ACTI_UNIT4' : '',
										'CONF_ACTI_UNIT4_ISO' : '',
										'CONF_ACTIVITY4' : '',
										'NO_REMN_ACTI4' : '',
										'CONF_ACTI_UNIT5' : '',
										'CONF_ACTI_UNIT5_ISO' : '',
										'CONF_ACTIVITY5' : '',
										'NO_REMN_ACTI5' : '',
										'CONF_ACTI_UNIT6' : '',
										'CONF_ACTI_UNIT6_ISO' : '',
										'CONF_ACTIVITY6' : '',
										'NO_REMN_ACTI6' : ''}]}}}}}

}

ZPPF_VB_READ_BATCH = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "ZPPF_VB_READ_BATCH",
				
				"parameterValues" : {
							'input' : 
				{'inputRoot' : 
				  {'TABLES' : 
				    {'T_C_MDBF' : 
				      {'item' : [
				        {'MATNR' : '',
				        'WERKS' : '',
				        'LGORT' : '',
				        'CHARG' : '',
				        'BWTAR' : '',
				        'SOBKZ' : '',
				        'LIFNR' : '',
				        'VBELN' : '',
				        'POSNR' : '',
				        'PSPNR' : '',
				        'LABST' : '',
				        'INSME' : '',
				        'EINME' : '',
				        'SPEME' : '',
				        'UMLME' : '',
				        'RETME' : '',
				        'VMLAB' : '',
				        'VMINS' : '',
				        'VMEIN' : '',
				        'VMSPE' : '',
				        'VMUML' : '',
				        'VMRET' : '',
				        'LVORM' : '',
				        'SPERR' : ''}]},
				    'T_E_MCHA' : 
				      {'item' : [
				        {'MANDT' : '',
				        'MATNR' : '',
				        'WERKS' : '',
				        'CHARG' : '',
				        'LVORM' : '',
				        'ERSDA' : '',
				        'ERNAM' : '',
				        'AENAM' : '',
				        'LAEDA' : '',
				        'VERAB' : '',
				        'VFDAT' : '',
				        'ZUSCH' : '',
				        'ZUSTD' : '',
				        'ZAEDT' : '',
				        'LIFNR' : '',
				        'LICHA' : '',
				        'VLCHA' : '',
				        'VLWRK' : '',
				        'VLMAT' : '',
				        'BWTAR' : '',
				        'CHAME' : '',
				        'LWEDT' : '',
				        'FVDT1' : '',
				        'FVDT2' : '',
				        'FVDT3' : '',
				        'FVDT4' : '',
				        'FVDT5' : '',
				        'FVDT6' : '',
				        'HERKL' : '',
				        'HERKR' : '',
				        'MTVER' : '',
				        'QNDAT' : '',
				        'HSDAT' : '',
				        'CUOBJ_BM' : '',
				        'DEACT_BM' : '',
				        'BATCH_TYPE' : '',
				        'SGT_SCAT' : '',
				        'ERSDA_TMSTP' : '',
				        'ERSDA_TZ_SYS' : '',
				        'ERSDA_TZ_USR' : '',
				        'FSH_SEASON_YEAR' : '',
				        'FSH_SEASON' : '',
				        'FSH_COLLECTION' : '',
				        'FSH_THEME' : ''}]},
				    'T_E_MCHB' : 
				      {'item' : [
				        {'MANDT' : '',
				        'MATNR' : '',
				        'WERKS' : '',
				        'LGORT' : '',
				        'CHARG' : '',
				        'LVORM' : '',
				        'ERSDA' : '',
				        'ERNAM' : '',
				        'LAEDA' : '',
				        'AENAM' : '',
				        'LFGJA' : '',
				        'LFMON' : '',
				        'SPERC' : '',
				        'CLABS' : '',
				        'CUMLM' : '',
				        'CINSM' : '',
				        'CEINM' : '',
				        'CSPEM' : '',
				        'CRETM' : '',
				        'CVMLA' : '',
				        'CVMUM' : '',
				        'CVMIN' : '',
				        'CVMEI' : '',
				        'CVMSP' : '',
				        'CVMRE' : '',
				        'KZICL' : '',
				        'KZICQ' : '',
				        'KZICE' : '',
				        'KZICS' : '',
				        'KZVCL' : '',
				        'KZVCQ' : '',
				        'KZVCE' : '',
				        'KZVCS' : '',
				        'HERKL' : '',
				        'CHDLL' : '',
				        'CHJIN' : '',
				        'CHRUE' : '',
				        'SGT_SCAT' : '',
				        'FSH_SEASON_YEAR' : '',
				        'FSH_SEASON' : '',
				        'FSH_COLLECTION' : '',
				        'FSH_THEME' : '',
				        'FSH_SALLOC_QTY' : ''}]},
				    'T_I_MCHB_KEY' : 
				      {'item' : [
				        {'MATNR' : '',
				        'WERKS' : '',
				        'LGORT' : '',
				        'CHARG' : '',
				        'MSGID' : '',
				        'MSGNO' : ''}]}},
				  'INPUT' : 
				    {'IM_I_FREE_STOCK_ONLY' : '',
				    'IM_I_NEW_READ' : '',
				    'I_INCL_DUMMY' : '',
				    'I_XRUEM' : ''}}}}
}

ZPPF_VC_I_GET_CONFIGURATION = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "ZPPF_VC_I_GET_CONFIGURATION",
				
				"parameterValues" : {'input' : 
				{'inputRoot' : 
				  {'INPUT' : 
				    {'I_INSTANCE' : '',
				    'I_LANGUAGE' : ''},
				  'TABLES' : 
				    {'T_CONFIGURATION' : 
				      {'item' : [
				        {'ATINN' : '',
				        'ATNAM' : '',
				        'ATBEZ' : '',
				        'ATWRT' : '',
				        'ATWTB' : '',
				        'EWAHR' : ''}]},
				    'T_CONFIGURATION_IDOC' : 
				      {'item' : [
				        {'ATINN' : '',
				        'ATNAM' : '',
				        'ATBEZ' : '',
				        'ATWRT' : '',
				        'ATWTB' : '',
				        'ATAUT' : ''}]}}}}
			}
}

#===============================================================================												  

ZPPF_WRAPPER_MAT_READ = {
		"returnThese": ['SAPReturn', 'output'],

		"bapi": "ZPPF_WRAPPER_MAT_READ",

		"parameterValues": {'input' : 
		{'inputRoot' : 
		  {'INPUT' : 
		    {'IV_MATNR' : ''},
		  'TABLES' : 
		    {'ET_ERROR' : 
		      {'item' : [
		        {'ZERROR' : ''}]},
		    'ET_ICDTXT_MATERIAL' : 
		      {'item' : [
		        {'TEILOBJID' : '',
		        'TEXTART' : '',
		        'TEXTSPR' : '',
		        'UPDKZ' : ''}]},
		    'ET_MAKT' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'SPRAS' : '',
		        'MAKTX' : '',
		        'MAKTG' : ''}]},
		    'ET_MARC' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'WERKS' : '',
		        'PSTAT' : '',
		        'LVORM' : '',
		        'BWTTY' : '',
		        'XCHAR' : '',
		        'MMSTA' : '',
		        'MMSTD' : '',
		        'MAABC' : '',
		        'KZKRI' : '',
		        'EKGRP' : '',
		        'AUSME' : '',
		        'DISPR' : '',
		        'DISMM' : '',
		        'DISPO' : '',
		        'KZDIE' : '',
		        'PLIFZ' : '',
		        'WEBAZ' : '',
		        'PERKZ' : '',
		        'AUSSS' : '',
		        'DISLS' : '',
		        'BESKZ' : '',
		        'SOBSL' : '',
		        'MINBE' : '',
		        'EISBE' : '',
		        'BSTMI' : '',
		        'BSTMA' : '',
		        'BSTFE' : '',
		        'BSTRF' : '',
		        'MABST' : '',
		        'LOSFX' : '',
		        'SBDKZ' : '',
		        'LAGPR' : '',
		        'ALTSL' : '',
		        'KZAUS' : '',
		        'AUSDT' : '',
		        'NFMAT' : '',
		        'KZBED' : '',
		        'MISKZ' : '',
		        'FHORI' : '',
		        'PFREI' : '',
		        'FFREI' : '',
		        'RGEKZ' : '',
		        'FEVOR' : '',
		        'BEARZ' : '',
		        'RUEZT' : '',
		        'TRANZ' : '',
		        'BASMG' : '',
		        'DZEIT' : '',
		        'MAXLZ' : '',
		        'LZEIH' : '',
		        'KZPRO' : '',
		        'GPMKZ' : '',
		        'UEETO' : '',
		        'UEETK' : '',
		        'UNETO' : '',
		        'WZEIT' : '',
		        'ATPKZ' : '',
		        'VZUSL' : '',
		        'HERBL' : '',
		        'INSMK' : '',
		        'SPROZ' : '',
		        'QUAZT' : '',
		        'SSQSS' : '',
		        'MPDAU' : '',
		        'KZPPV' : '',
		        'KZDKZ' : '',
		        'WSTGH' : '',
		        'PRFRQ' : '',
		        'NKMPR' : '',
		        'UMLMC' : '',
		        'LADGR' : '',
		        'XCHPF' : '',
		        'USEQU' : '',
		        'LGRAD' : '',
		        'AUFTL' : '',
		        'PLVAR' : '',
		        'OTYPE' : '',
		        'OBJID' : 0,
		        'MTVFP' : '',
		        'PERIV' : '',
		        'KZKFK' : '',
		        'VRVEZ' : '',
		        'VBAMG' : '',
		        'VBEAZ' : '',
		        'LIZYK' : '',
		        'BWSCL' : '',
		        'KAUTB' : '',
		        'KORDB' : '',
		        'STAWN' : '',
		        'HERKL' : '',
		        'HERKR' : '',
		        'EXPME' : '',
		        'MTVER' : '',
		        'PRCTR' : '',
		        'TRAME' : '',
		        'MRPPP' : '',
		        'SAUFT' : '',
		        'FXHOR' : 0,
		        'VRMOD' : '',
		        'VINT1' : 0,
		        'VINT2' : 0,
		        'VERKZ' : '',
		        'STLAL' : '',
		        'STLAN' : '',
		        'PLNNR' : '',
		        'APLAL' : '',
		        'LOSGR' : '',
		        'SOBSK' : '',
		        'FRTME' : '',
		        'LGPRO' : '',
		        'DISGR' : '',
		        'KAUSF' : '',
		        'QZGTP' : '',
		        'QMATV' : '',
		        'TAKZT' : '',
		        'RWPRO' : '',
		        'COPAM' : '',
		        'ABCIN' : '',
		        'AWSLS' : '',
		        'SERNP' : '',
		        'CUOBJ' : 0,
		        'STDPD' : '',
		        'SFEPR' : '',
		        'XMCNG' : '',
		        'QSSYS' : '',
		        'LFRHY' : '',
		        'RDPRF' : '',
		        'VRBMT' : '',
		        'VRBWK' : '',
		        'VRBDT' : '',
		        'VRBFK' : '',
		        'AUTRU' : '',
		        'PREFE' : '',
		        'PRENC' : '',
		        'PRENO' : '',
		        'PREND' : '',
		        'PRENE' : '',
		        'PRENG' : '',
		        'ITARK' : '',
		        'SERVG' : '',
		        'KZKUP' : '',
		        'STRGR' : '',
		        'CUOBV' : 0,
		        'LGFSB' : '',
		        'SCHGT' : '',
		        'CCFIX' : '',
		        'EPRIO' : '',
		        'QMATA' : '',
		        'RESVP' : '',
		        'PLNTY' : '',
		        'UOMGR' : '',
		        'UMRSL' : '',
		        'ABFAC' : '',
		        'SFCPF' : '',
		        'SHFLG' : '',
		        'SHZET' : 0,
		        'MDACH' : '',
		        'KZECH' : '',
		        'MEGRU' : '',
		        'MFRGR' : '',
		        'VKUMC' : '',
		        'VKTRW' : '',
		        'KZAGL' : '',
		        'FVIDK' : '',
		        'FXPRU' : '',
		        'LOGGR' : '',
		        'FPRFM' : '',
		        'GLGMG' : '',
		        'VKGLG' : '',
		        'INDUS' : '',
		        'MOWNR' : '',
		        'MOGRU' : '',
		        'CASNR' : '',
		        'GPNUM' : '',
		        'STEUC' : '',
		        'FABKZ' : '',
		        'MATGR' : '',
		        'VSPVB' : '',
		        'DPLFS' : '',
		        'DPLPU' : '',
		        'DPLHO' : '',
		        'MINLS' : '',
		        'MAXLS' : '',
		        'FIXLS' : '',
		        'LTINC' : '',
		        'COMPL' : 0,
		        'CONVT' : '',
		        'SHPRO' : '',
		        'AHDIS' : '',
		        'DIBER' : '',
		        'KZPSP' : '',
		        'OCMPF' : '',
		        'APOKZ' : '',
		        'MCRUE' : '',
		        'LFMON' : 0,
		        'LFGJA' : 0,
		        'EISLO' : '',
		        'NCOST' : '',
		        'ROTATION_DATE' : '',
		        'UCHKZ' : '',
		        'UCMAT' : '',
		        'BWESB' : '',
		        'SGT_COVS' : '',
		        'SGT_STATC' : '',
		        'SGT_SCOPE' : '',
		        'SGT_MRPSI' : '',
		        'SGT_PRCM' : '',
		        'SGT_CHINT' : '',
		        'SGT_STK_PRT' : '',
		        'SGT_DEFSC' : '',
		        'SGT_MRP_ATP_STATUS' : '',
		        'SGT_MMSTD' : '',
		        'FSH_MG_ARUN_REQ' : '',
		        'FSH_SEAIM' : '',
		        'FSH_VAR_GROUP' : '',
		        'FSH_KZECH' : '',
		        'FSH_CALENDAR_GROUP' : '',
		        'PPSKZ' : '',
		        'PPS_STRATEGY' : '',
		        'PPS_PLANNING_TYPE' : '',
		        'PPS_HEUR_ID' : '',
		        'PPS_FIXPEG' : '',
		        'PPS_PEG_STRATEGY' : 0,
		        'PPS_GRPRT' : '',
		        'PPS_GIPRT' : '',
		        'PPS_CONHAP' : '',
		        'PPS_HUNIT' : '',
		        'PPS_CONHAP_OUT' : '',
		        'PPS_HUNIT_OUT' : '',
		        'PPS_ATPCHECK' : '',
		        'PPS_PEG_FUT_AL' : '',
		        'PPS_PEG_PAST_AL' : '',
		        '_--2FSAPMP_--2FTOLPRPL' : '',
		        '_--2FSAPMP_--2FTOLPRMI' : '',
		        '_--2FVSO_--2FR_PKGRP' : '',
		        '_--2FVSO_--2FR_LANE_NUM' : '',
		        '_--2FVSO_--2FR_PAL_VEND' : '',
		        '_--2FVSO_--2FR_FORK_DIR' : '',
		        'IUID_RELEVANT' : '',
		        'IUID_TYPE' : '',
		        'UID_IEA' : '',
		        'CONS_PROCG' : '',
		        'GI_PR_TIME' : '',
		        'MULTIPLE_EKGRP' : '',
		        'REF_SCHEMA' : '',
		        'MIN_TROC' : 0,
		        'MAX_TROC' : 0,
		        'TARGET_STOCK' : '',
		        'ZZOLDNR' : '',
		        'ZZLAUNCHD' : '',
		        'ZZIOA' : '',
		        'ZZPRD' : '',
		        'ZZCHANNEL' : ''}]},
		    'ET_MARD' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'WERKS' : '',
		        'LGORT' : '',
		        'PSTAT' : '',
		        'LVORM' : '',
		        'LFGJA' : 0,
		        'LFMON' : 0,
		        'SPERR' : '',
		        'LABST' : '',
		        'UMLME' : '',
		        'INSME' : '',
		        'EINME' : '',
		        'SPEME' : '',
		        'RETME' : '',
		        'VMLAB' : '',
		        'VMUML' : '',
		        'VMINS' : '',
		        'VMEIN' : '',
		        'VMSPE' : '',
		        'VMRET' : '',
		        'KZILL' : '',
		        'KZILQ' : '',
		        'KZILE' : '',
		        'KZILS' : '',
		        'KZVLL' : '',
		        'KZVLQ' : '',
		        'KZVLE' : '',
		        'KZVLS' : '',
		        'DISKZ' : '',
		        'LSOBS' : '',
		        'LMINB' : '',
		        'LBSTF' : '',
		        'HERKL' : '',
		        'EXPPG' : '',
		        'EXVER' : '',
		        'LGPBE' : '',
		        'KLABS' : '',
		        'KINSM' : '',
		        'KEINM' : '',
		        'KSPEM' : '',
		        'DLINL' : '',
		        'PRCTL' : '',
		        'ERSDA' : '',
		        'VKLAB' : '',
		        'VKUML' : '',
		        'LWMKB' : '',
		        'BSKRF' : 0,
		        'MDRUE' : '',
		        'MDJIN' : 0,
		        'FSH_SALLOC_QTY_S' : ''}]},
		    'ET_MARM' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'MEINH' : '',
		        'UMREZ' : '',
		        'UMREN' : '',
		        'EANNR' : '',
		        'EAN11' : '',
		        'NUMTP' : '',
		        'LAENG' : '',
		        'BREIT' : '',
		        'HOEHE' : '',
		        'MEABM' : '',
		        'VOLUM' : '',
		        'VOLEH' : '',
		        'BRGEW' : '',
		        'GEWEI' : '',
		        'MESUB' : '',
		        'ATINN' : 0,
		        'MESRT' : 0,
		        'XFHDW' : '',
		        'XBEWW' : '',
		        'KZWSO' : '',
		        'MSEHI' : '',
		        'BFLME_MARM' : '',
		        'GTIN_VARIANT' : '',
		        'NEST_FTR' : '',
		        'MAX_STACK' : 0,
		        'CAPAUSE' : '',
		        'TY2TQ' : ''}]},
		    'ET_MBEW' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'BWKEY' : '',
		        'BWTAR' : '',
		        'LVORM' : '',
		        'LBKUM' : '',
		        'SALK3' : '',
		        'VPRSV' : '',
		        'VERPR' : '',
		        'STPRS' : '',
		        'PEINH' : '',
		        'BKLAS' : '',
		        'SALKV' : '',
		        'VMKUM' : '',
		        'VMSAL' : '',
		        'VMVPR' : '',
		        'VMVER' : '',
		        'VMSTP' : '',
		        'VMPEI' : '',
		        'VMBKL' : '',
		        'VMSAV' : '',
		        'VJKUM' : '',
		        'VJSAL' : '',
		        'VJVPR' : '',
		        'VJVER' : '',
		        'VJSTP' : '',
		        'VJPEI' : '',
		        'VJBKL' : '',
		        'VJSAV' : '',
		        'LFGJA' : 0,
		        'LFMON' : 0,
		        'BWTTY' : '',
		        'STPRV' : '',
		        'LAEPR' : '',
		        'ZKPRS' : '',
		        'ZKDAT' : '',
		        'TIMESTAMP' : '',
		        'BWPRS' : '',
		        'BWPRH' : '',
		        'VJBWS' : '',
		        'VJBWH' : '',
		        'VVJSL' : '',
		        'VVJLB' : '',
		        'VVMLB' : '',
		        'VVSAL' : '',
		        'ZPLPR' : '',
		        'ZPLP1' : '',
		        'ZPLP2' : '',
		        'ZPLP3' : '',
		        'ZPLD1' : '',
		        'ZPLD2' : '',
		        'ZPLD3' : '',
		        'PPERZ' : 0,
		        'PPERL' : 0,
		        'PPERV' : 0,
		        'KALKZ' : '',
		        'KALKL' : '',
		        'KALKV' : '',
		        'KALSC' : '',
		        'XLIFO' : '',
		        'MYPOL' : '',
		        'BWPH1' : '',
		        'BWPS1' : '',
		        'ABWKZ' : 0,
		        'PSTAT' : '',
		        'KALN1' : 0,
		        'KALNR' : 0,
		        'BWVA1' : '',
		        'BWVA2' : '',
		        'BWVA3' : '',
		        'VERS1' : 0,
		        'VERS2' : 0,
		        'VERS3' : 0,
		        'HRKFT' : '',
		        'KOSGR' : '',
		        'PPRDZ' : 0,
		        'PPRDL' : 0,
		        'PPRDV' : 0,
		        'PDATZ' : 0,
		        'PDATL' : 0,
		        'PDATV' : 0,
		        'EKALR' : '',
		        'VPLPR' : '',
		        'MLMAA' : '',
		        'MLAST' : '',
		        'LPLPR' : '',
		        'VKSAL' : '',
		        'HKMAT' : '',
		        'SPERW' : '',
		        'KZIWL' : '',
		        'WLINL' : '',
		        'ABCIW' : '',
		        'BWSPA' : '',
		        'LPLPX' : '',
		        'VPLPX' : '',
		        'FPLPX' : '',
		        'LBWST' : '',
		        'VBWST' : '',
		        'FBWST' : '',
		        'EKLAS' : '',
		        'QKLAS' : '',
		        'MTUSE' : '',
		        'MTORG' : '',
		        'OWNPR' : '',
		        'XBEWM' : '',
		        'BWPEI' : '',
		        'MBRUE' : '',
		        'OKLAS' : '',
		        'OIPPINV' : ''}]},
		    'ET_MEAN' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'MEINH' : '',
		        'LFNUM' : '',
		        'EAN11' : '',
		        'EANTP' : '',
		        'HPEAN' : '',
		        'SGT_CATV' : ''}]},
		    'ET_MLAN' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'ALAND' : '',
		        'TAXM1' : '',
		        'TAXM2' : '',
		        'TAXM3' : '',
		        'TAXM4' : '',
		        'TAXM5' : '',
		        'TAXM6' : '',
		        'TAXM7' : '',
		        'TAXM8' : '',
		        'TAXM9' : '',
		        'TAXIM' : ''}]},
		    'ET_MVKE' : 
		      {'item' : [
		        {'MANDT' : '',
		        'MATNR' : '',
		        'VKORG' : '',
		        'VTWEG' : '',
		        'LVORM' : '',
		        'VERSG' : '',
		        'BONUS' : '',
		        'PROVG' : '',
		        'SKTOF' : '',
		        'VMSTA' : '',
		        'VMSTD' : '',
		        'AUMNG' : '',
		        'LFMNG' : '',
		        'EFMNG' : '',
		        'SCMNG' : '',
		        'SCHME' : '',
		        'VRKME' : '',
		        'MTPOS' : '',
		        'DWERK' : '',
		        'PRODH' : '',
		        'PMATN' : '',
		        'KONDM' : '',
		        'KTGRM' : '',
		        'MVGR1' : '',
		        'MVGR2' : '',
		        'MVGR3' : '',
		        'MVGR4' : '',
		        'MVGR5' : '',
		        'SSTUF' : '',
		        'PFLKS' : '',
		        'LSTFL' : '',
		        'LSTVZ' : '',
		        'LSTAK' : '',
		        'LDVFL' : '',
		        'LDBFL' : '',
		        'LDVZL' : '',
		        'LDBZL' : '',
		        'VDVFL' : '',
		        'VDBFL' : '',
		        'VDVZL' : '',
		        'VDBZL' : '',
		        'PRAT1' : '',
		        'PRAT2' : '',
		        'PRAT3' : '',
		        'PRAT4' : '',
		        'PRAT5' : '',
		        'PRAT6' : '',
		        'PRAT7' : '',
		        'PRAT8' : '',
		        'PRAT9' : '',
		        'PRATA' : '',
		        'RDPRF' : '',
		        'MEGRU' : '',
		        'LFMAX' : '',
		        'RJART' : '',
		        'PBIND' : '',
		        'VAVME' : '',
		        'MATKC' : '',
		        'PVMSO' : 0,
		        '_--2FBEV1_--2FEMLGRP' : '',
		        '_--2FBEV1_--2FEMDRCKSPL' : 0,
		        '_--2FBEV1_--2FRPBEZME' : '',
		        '_--2FBEV1_--2FRPSNS' : '',
		        '_--2FBEV1_--2FRPSFA' : '',
		        '_--2FBEV1_--2FRPSKI' : '',
		        '_--2FBEV1_--2FRPSCO' : '',
		        '_--2FBEV1_--2FRPSSO' : '',
		        'PLGTP' : '',
		        'ZZAUMNG1' : '',
		        'ZZSCMNG1' : '',
		        'ZZSCHME1' : '',
		        'ZZRDPRF1' : '',
		        'ZZLMKTD' : '',
		        'ZZLRCODE' : '',
		        'ZZSALES' : ''}]},
		    'ET_XDMAKT' : 
		      {'item' : [
		        {'SPRAS' : '',
		        'MAKTX' : '',
		        'KZ' : ''}]},
		    'ET_XDMARC' : 
		      {'item' : [
		        {'WERKS' : '',
		        'PSTAT' : '',
		        'LVORM' : '',
		        'BWTTY' : '',
		        'XCHAR' : '',
		        'MMSTA' : '',
		        'MMSTD' : '',
		        'MAABC' : '',
		        'KZKRI' : '',
		        'EKGRP' : '',
		        'AUSME' : '',
		        'DISPR' : '',
		        'DISMM' : '',
		        'DISPO' : '',
		        'KZDIE' : '',
		        'PLIFZ' : '',
		        'WEBAZ' : '',
		        'PERKZ' : '',
		        'AUSSS' : '',
		        'DISLS' : '',
		        'BESKZ' : '',
		        'SOBSL' : '',
		        'MINBE' : '',
		        'EISBE' : '',
		        'BSTMI' : '',
		        'BSTMA' : '',
		        'BSTFE' : '',
		        'BSTRF' : '',
		        'MABST' : '',
		        'LOSFX' : '',
		        'SBDKZ' : '',
		        'LAGPR' : '',
		        'ALTSL' : '',
		        'KZAUS' : '',
		        'AUSDT' : '',
		        'NFMAT' : '',
		        'KZBED' : '',
		        'MISKZ' : '',
		        'FHORI' : '',
		        'PFREI' : '',
		        'FFREI' : '',
		        'RGEKZ' : '',
		        'FEVOR' : '',
		        'BEARZ' : '',
		        'RUEZT' : '',
		        'TRANZ' : '',
		        'BASMG' : '',
		        'DZEIT' : '',
		        'MAXLZ' : '',
		        'LZEIH' : '',
		        'KZPRO' : '',
		        'GPMKZ' : '',
		        'UEETO' : '',
		        'UEETK' : '',
		        'UNETO' : '',
		        'WZEIT' : '',
		        'ATPKZ' : '',
		        'VZUSL' : '',
		        'HERBL' : '',
		        'INSMK' : '',
		        'SPROZ' : '',
		        'QUAZT' : '',
		        'SSQSS' : '',
		        'MPDAU' : '',
		        'KZPPV' : '',
		        'KZDKZ' : '',
		        'WSTGH' : '',
		        'PRFRQ' : '',
		        'NKMPR' : '',
		        'UMLMC' : '',
		        'LADGR' : '',
		        'XCHPF' : '',
		        'USEQU' : '',
		        'LGRAD' : '',
		        'AUFTL' : '',
		        'PLVAR' : '',
		        'OTYPE' : '',
		        'OBJID' : 0,
		        'MTVFP' : '',
		        'PERIV' : '',
		        'KZKFK' : '',
		        'VRVEZ' : '',
		        'VBAMG' : '',
		        'VBEAZ' : '',
		        'LIZYK' : '',
		        'BWSCL' : '',
		        'KAUTB' : '',
		        'KORDB' : '',
		        'STAWN' : '',
		        'HERKL' : '',
		        'HERKR' : '',
		        'EXPME' : '',
		        'MTVER' : '',
		        'PRCTR' : '',
		        'TRAME' : '',
		        'MRPPP' : '',
		        'SAUFT' : '',
		        'FXHOR' : 0,
		        'VRMOD' : '',
		        'VINT1' : 0,
		        'VINT2' : 0,
		        'VERKZ' : '',
		        'STLAL' : '',
		        'STLAN' : '',
		        'PLNNR' : '',
		        'APLAL' : '',
		        'LOSGR' : '',
		        'SOBSK' : '',
		        'FRTME' : '',
		        'LGPRO' : '',
		        'DISGR' : '',
		        'KAUSF' : '',
		        'QZGTP' : '',
		        'QMATV' : '',
		        'TAKZT' : '',
		        'RWPRO' : '',
		        'COPAM' : '',
		        'ABCIN' : '',
		        'AWSLS' : '',
		        'SERNP' : '',
		        'CUOBJ' : 0,
		        'STDPD' : '',
		        'SFEPR' : '',
		        'XMCNG' : '',
		        'QSSYS' : '',
		        'LFRHY' : '',
		        'RDPRF' : '',
		        'VRBMT' : '',
		        'VRBWK' : '',
		        'VRBDT' : '',
		        'VRBFK' : '',
		        'AUTRU' : '',
		        'PREFE' : '',
		        'PRENC' : '',
		        'PRENO' : '',
		        'PREND' : '',
		        'PRENE' : '',
		        'PRENG' : '',
		        'ITARK' : '',
		        'SERVG' : '',
		        'KZKUP' : '',
		        'STRGR' : '',
		        'CUOBV' : 0,
		        'LGFSB' : '',
		        'SCHGT' : '',
		        'CCFIX' : '',
		        'EPRIO' : '',
		        'QMATA' : '',
		        'RESVP' : '',
		        'PLNTY' : '',
		        'UOMGR' : '',
		        'UMRSL' : '',
		        'ABFAC' : '',
		        'SFCPF' : '',
		        'SHFLG' : '',
		        'SHZET' : 0,
		        'MDACH' : '',
		        'KZECH' : '',
		        'MEGRU' : '',
		        'MFRGR' : '',
		        'VKUMC' : '',
		        'VKTRW' : '',
		        'KZAGL' : '',
		        'FVIDK' : '',
		        'FXPRU' : '',
		        'LOGGR' : '',
		        'FPRFM' : '',
		        'GLGMG' : '',
		        'VKGLG' : '',
		        'INDUS' : '',
		        'MOWNR' : '',
		        'MOGRU' : '',
		        'CASNR' : '',
		        'GPNUM' : '',
		        'STEUC' : '',
		        'FABKZ' : '',
		        'MATGR' : '',
		        'VSPVB' : '',
		        'DPLFS' : '',
		        'DPLPU' : '',
		        'DPLHO' : '',
		        'MINLS' : '',
		        'MAXLS' : '',
		        'FIXLS' : '',
		        'LTINC' : '',
		        'COMPL' : 0,
		        'CONVT' : '',
		        'SHPRO' : '',
		        'AHDIS' : '',
		        'DIBER' : '',
		        'KZPSP' : '',
		        'OCMPF' : '',
		        'APOKZ' : '',
		        'MCRUE' : '',
		        'LFMON' : 0,
		        'LFGJA' : 0,
		        'EISLO' : '',
		        'NCOST' : '',
		        'ROTATION_DATE' : '',
		        'UCHKZ' : '',
		        'UCMAT' : '',
		        'BWESB' : '',
		        'SGT_COVS' : '',
		        'SGT_STATC' : '',
		        'SGT_SCOPE' : '',
		        'SGT_MRPSI' : '',
		        'SGT_PRCM' : '',
		        'SGT_CHINT' : '',
		        'SGT_STK_PRT' : '',
		        'SGT_DEFSC' : '',
		        'SGT_MRP_ATP_STATUS' : '',
		        'SGT_MMSTD' : '',
		        'FSH_MG_ARUN_REQ' : '',
		        'FSH_SEAIM' : '',
		        'FSH_VAR_GROUP' : '',
		        'FSH_KZECH' : '',
		        'FSH_CALENDAR_GROUP' : '',
		        'PPSKZ' : '',
		        'PPS_STRATEGY' : '',
		        'PPS_PLANNING_TYPE' : '',
		        'PPS_HEUR_ID' : '',
		        'PPS_FIXPEG' : '',
		        'PPS_PEG_STRATEGY' : 0,
		        'PPS_GRPRT' : '',
		        'PPS_GIPRT' : '',
		        'PPS_CONHAP' : '',
		        'PPS_HUNIT' : '',
		        'PPS_CONHAP_OUT' : '',
		        'PPS_HUNIT_OUT' : '',
		        'PPS_ATPCHECK' : '',
		        'PPS_PEG_FUT_AL' : '',
		        'PPS_PEG_PAST_AL' : '',
		        '_--2FSAPMP_--2FTOLPRPL' : '',
		        '_--2FSAPMP_--2FTOLPRMI' : '',
		        '_--2FVSO_--2FR_PKGRP' : '',
		        '_--2FVSO_--2FR_LANE_NUM' : '',
		        '_--2FVSO_--2FR_PAL_VEND' : '',
		        '_--2FVSO_--2FR_FORK_DIR' : '',
		        'IUID_RELEVANT' : '',
		        'IUID_TYPE' : '',
		        'UID_IEA' : '',
		        'CONS_PROCG' : '',
		        'GI_PR_TIME' : '',
		        'MULTIPLE_EKGRP' : '',
		        'REF_SCHEMA' : '',
		        'MIN_TROC' : 0,
		        'MAX_TROC' : 0,
		        'TARGET_STOCK' : '',
		        'KZ' : '',
		        'MARAMEINS' : '',
		        'T001WAERS' : ''}]},
		    'ET_XDMARD' : 
		      {'item' : [
		        {'WERKS' : '',
		        'LGORT' : '',
		        'PSTAT' : '',
		        'LVORM' : '',
		        'LFGJA' : 0,
		        'LFMON' : 0,
		        'SPERR' : '',
		        'LABST' : '',
		        'UMLME' : '',
		        'INSME' : '',
		        'EINME' : '',
		        'SPEME' : '',
		        'RETME' : '',
		        'VMLAB' : '',
		        'VMUML' : '',
		        'VMINS' : '',
		        'VMEIN' : '',
		        'VMSPE' : '',
		        'VMRET' : '',
		        'KZILL' : '',
		        'KZILQ' : '',
		        'KZILE' : '',
		        'KZILS' : '',
		        'KZVLL' : '',
		        'KZVLQ' : '',
		        'KZVLE' : '',
		        'KZVLS' : '',
		        'DISKZ' : '',
		        'LSOBS' : '',
		        'LMINB' : '',
		        'LBSTF' : '',
		        'HERKL' : '',
		        'EXPPG' : '',
		        'EXVER' : '',
		        'LGPBE' : '',
		        'KLABS' : '',
		        'KINSM' : '',
		        'KEINM' : '',
		        'KSPEM' : '',
		        'DLINL' : '',
		        'PRCTL' : '',
		        'ERSDA' : '',
		        'VKLAB' : '',
		        'VKUML' : '',
		        'LWMKB' : '',
		        'BSKRF' : 0,
		        'MDRUE' : '',
		        'MDJIN' : 0,
		        'KZ' : '',
		        'MARAMEINS' : '',
		        'T001WAERS' : ''}]},
		    'ET_XDMARM' : 
		      {'item' : [
		        {'MEINH' : '',
		        'UMREZ' : '',
		        'UMREN' : '',
		        'EANNR' : '',
		        'EAN11' : '',
		        'NUMTP' : '',
		        'LAENG' : '',
		        'BREIT' : '',
		        'HOEHE' : '',
		        'MEABM' : '',
		        'VOLUM' : '',
		        'VOLEH' : '',
		        'BRGEW' : '',
		        'GEWEI' : '',
		        'MESUB' : '',
		        'ATINN' : 0,
		        'MESRT' : 0,
		        'XFHDW' : '',
		        'XBEWW' : '',
		        'KZWSO' : '',
		        'MSEHI' : '',
		        'GTIN_VARIANT' : '',
		        'NEST_FTR' : '',
		        'MAX_STACK' : 0,
		        'CAPAUSE' : '',
		        'TY2TQ' : '',
		        'KZ' : ''}]},
		    'ET_XDMBEW' : 
		      {'item' : [
		        {'BWKEY' : '',
		        'BWTAR' : '',
		        'LVORM' : '',
		        'LBKUM' : '',
		        'SALK3' : '',
		        'VPRSV' : '',
		        'VERPR' : '',
		        'STPRS' : '',
		        'PEINH' : '',
		        'BKLAS' : '',
		        'SALKV' : '',
		        'VMKUM' : '',
		        'VMSAL' : '',
		        'VMVPR' : '',
		        'VMVER' : '',
		        'VMSTP' : '',
		        'VMPEI' : '',
		        'VMBKL' : '',
		        'VMSAV' : '',
		        'VJKUM' : '',
		        'VJSAL' : '',
		        'VJVPR' : '',
		        'VJVER' : '',
		        'VJSTP' : '',
		        'VJPEI' : '',
		        'VJBKL' : '',
		        'VJSAV' : '',
		        'LFGJA' : 0,
		        'LFMON' : 0,
		        'BWTTY' : '',
		        'STPRV' : '',
		        'LAEPR' : '',
		        'ZKPRS' : '',
		        'ZKDAT' : '',
		        'TIMESTAMP' : '',
		        'BWPRS' : '',
		        'BWPRH' : '',
		        'VJBWS' : '',
		        'VJBWH' : '',
		        'VVJSL' : '',
		        'VVJLB' : '',
		        'VVMLB' : '',
		        'VVSAL' : '',
		        'ZPLPR' : '',
		        'ZPLP1' : '',
		        'ZPLP2' : '',
		        'ZPLP3' : '',
		        'ZPLD1' : '',
		        'ZPLD2' : '',
		        'ZPLD3' : '',
		        'PPERZ' : 0,
		        'PPERL' : 0,
		        'PPERV' : 0,
		        'KALKZ' : '',
		        'KALKL' : '',
		        'KALKV' : '',
		        'KALSC' : '',
		        'XLIFO' : '',
		        'MYPOL' : '',
		        'BWPH1' : '',
		        'BWPS1' : '',
		        'ABWKZ' : 0,
		        'PSTAT' : '',
		        'KALN1' : 0,
		        'KALNR' : 0,
		        'BWVA1' : '',
		        'BWVA2' : '',
		        'BWVA3' : '',
		        'VERS1' : 0,
		        'VERS2' : 0,
		        'VERS3' : 0,
		        'HRKFT' : '',
		        'KOSGR' : '',
		        'PPRDZ' : 0,
		        'PPRDL' : 0,
		        'PPRDV' : 0,
		        'PDATZ' : 0,
		        'PDATL' : 0,
		        'PDATV' : 0,
		        'EKALR' : '',
		        'VPLPR' : '',
		        'MLMAA' : '',
		        'MLAST' : '',
		        'LPLPR' : '',
		        'VKSAL' : '',
		        'HKMAT' : '',
		        'SPERW' : '',
		        'KZIWL' : '',
		        'WLINL' : '',
		        'ABCIW' : '',
		        'BWSPA' : '',
		        'LPLPX' : '',
		        'VPLPX' : '',
		        'FPLPX' : '',
		        'LBWST' : '',
		        'VBWST' : '',
		        'FBWST' : '',
		        'EKLAS' : '',
		        'QKLAS' : '',
		        'MTUSE' : '',
		        'MTORG' : '',
		        'OWNPR' : '',
		        'XBEWM' : '',
		        'BWPEI' : '',
		        'MBRUE' : '',
		        'OKLAS' : '',
		        'OIPPINV' : '',
		        'KZ' : '',
		        'MARAMEINS' : '',
		        'T001WAERS' : ''}]},
		    'ET_XDMEAN' : 
		      {'item' : [
		        {'MEINH' : '',
		        'EAN11' : '',
		        'EANTP' : '',
		        'KZ' : ''}]},
		    'ET_XDMLAN' : 
		      {'item' : [
		        {'ALAND' : '',
		        'TATYP' : '',
		        'TAXKM' : '',
		        'KZ' : ''}]},
		    'ET_XDMVKE' : 
		      {'item' : [
		        {'VKORG' : '',
		        'VTWEG' : '',
		        'LVORM' : '',
		        'VERSG' : '',
		        'BONUS' : '',
		        'PROVG' : '',
		        'SKTOF' : '',
		        'VMSTA' : '',
		        'VMSTD' : '',
		        'AUMNG' : '',
		        'LFMNG' : '',
		        'EFMNG' : '',
		        'SCMNG' : '',
		        'SCHME' : '',
		        'VRKME' : '',
		        'MTPOS' : '',
		        'DWERK' : '',
		        'PRODH' : '',
		        'PMATN' : '',
		        'KONDM' : '',
		        'KTGRM' : '',
		        'MVGR1' : '',
		        'MVGR2' : '',
		        'MVGR3' : '',
		        'MVGR4' : '',
		        'MVGR5' : '',
		        'SSTUF' : '',
		        'PFLKS' : '',
		        'LSTFL' : '',
		        'LSTVZ' : '',
		        'LSTAK' : '',
		        'LDVFL' : '',
		        'LDBFL' : '',
		        'LDVZL' : '',
		        'LDBZL' : '',
		        'VDVFL' : '',
		        'VDBFL' : '',
		        'VDVZL' : '',
		        'VDBZL' : '',
		        'PRAT1' : '',
		        'PRAT2' : '',
		        'PRAT3' : '',
		        'PRAT4' : '',
		        'PRAT5' : '',
		        'PRAT6' : '',
		        'PRAT7' : '',
		        'PRAT8' : '',
		        'PRAT9' : '',
		        'PRATA' : '',
		        'RDPRF' : '',
		        'MEGRU' : '',
		        'LFMAX' : '',
		        'RJART' : '',
		        'PBIND' : '',
		        'VAVME' : '',
		        'MATKC' : '',
		        'PVMSO' : 0,
		        '_--2FBEV1_--2FEMLGRP' : '',
		        '_--2FBEV1_--2FEMDRCKSPL' : 0,
		        '_--2FBEV1_--2FRPBEZME' : '',
		        '_--2FBEV1_--2FRPSNS' : '',
		        '_--2FBEV1_--2FRPSFA' : '',
		        '_--2FBEV1_--2FRPSKI' : '',
		        '_--2FBEV1_--2FRPSCO' : '',
		        '_--2FBEV1_--2FRPSSO' : '',
		        'PLGTP' : '',
		        'KZ' : '',
		        'MARAMEINS' : '',
		        'T001WAERS' : ''}]}}}}}}
		        
		        
#==========================================================
ZPPF_MARA_READ = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "ZPPF_MARA_READ",
				
				"parameterValues" : {'input' : 
				{'inputRoot' : 
				  {'INPUT' : 
				    {'IM_MATNR' : '',
				    'IM_SPRACHE' : 'EN'}}}
			}
}

#==========================================================
BAPI_PO_GETITEMS = {
				"returnThese" : ['input', 'SAPReturn', 'output'],
		
				"bapi" : "BAPI_PO_GETITEMS",
				
				"parameterValues" : {'input' : 
				{'inputRoot' : 
				  {'INPUT' : 
				    {'ACCTASSCAT' : '',
				    'CREATED_BY' : '',
				    'DELETED_ITEMS' : '',
				    'DOC_DATE' : '',
				    'DOC_TYPE' : '',
				    'ITEMS_OPEN_FOR_RECEIPT' : '',
				    'ITEM_CAT' : '',
				    'MATERIAL' : '',
				    'MATERIAL_LONG' : '',
				    'MAT_GRP' : '',
				    'PLANT' : '',
				    'PREQ_NAME' : '',
				    'PURCHASEORDER' : '',
				    'PURCH_ORG' : '',
				    'PUR_GROUP' : '',
				    'PUR_MAT' : '',
				    'PUR_MAT_LONG' : '',
				    'SHORT_TEXT' : '',
				    'SUPPL_PLANT' : '',
				    'TRACKINGNO' : '',
				    'VENDOR' : '',
				    'WITH_PO_HEADERS' : '',
				    'MATERIAL_EVG' : 
				      {'MATERIAL_EXT' : '',
				      'MATERIAL_VERS' : '',
				      'MATERIAL_GUID' : ''},
				    'PUR_MAT_EVG' : 
				      {'MATERIAL_EXT' : '',
				      'MATERIAL_VERS' : '',
				      'MATERIAL_GUID' : ''}},
				  'TABLES' : 
				    {'PO_HEADERS' : 
				      {'item' : [
				        {'PO_NUMBER' : '',
				        'CO_CODE' : '',
				        'DOC_CAT' : '',
				        'DOC_TYPE' : '',
				        'CNTRL_IND' : '',
				        'DELETE_IND' : '',
				        'STATUS' : '',
				        'CREATED_ON' : '',
				        'CREATED_BY' : '',
				        'ITEM_INTVL' : '',
				        'LAST_ITEM' : '',
				        'VENDOR' : '',
				        'LANGUAGE' : '',
				        'PMNTTRMS' : '',
				        'DSCNT1_TO' : '',
				        'DSCNT2_TO' : '',
				        'DSCNT3_TO' : '',
				        'CASH_DISC1' : '',
				        'CASH_DISC2' : '',
				        'PURCH_ORG' : '',
				        'PUR_GROUP' : '',
				        'CURRENCY' : '',
				        'EXCH_RATE' : '',
				        'EX_RATE_FX' : '',
				        'DOC_DATE' : '',
				        'VPER_START' : '',
				        'VPER_END' : '',
				        'APPLIC_BY' : '',
				        'QUOT_DEAD' : '',
				        'BINDG_PER' : '',
				        'WARRANTY' : '',
				        'BIDINV_NO' : '',
				        'QUOTATION' : '',
				        'QUOT_DATE' : '',
				        'REF_1' : '',
				        'SALES_PERS' : '',
				        'TELEPHONE' : '',
				        'SUPPL_VEND' : '',
				        'CUSTOMER' : '',
				        'AGREEMENT' : '',
				        'REJ_REASON' : '',
				        'COMPL_DLV' : '',
				        'GR_MESSAGE' : '',
				        'SUPPL_PLNT' : '',
				        'RCVG_VEND' : '',
				        'INCOTERMS1' : '',
				        'INCOTERMS2' : '',
				        'TARGET_VAL' : '',
				        'COLL_NO' : '',
				        'DOC_COND' : '',
				        'PROCEDURE' : '',
				        'UPDATE_GRP' : '',
				        'DIFF_INV' : '',
				        'EXPORT_NO' : '',
				        'OUR_REF' : '',
				        'LOGSYSTEM' : '',
				        'SUBITEMINT' : '',
				        'MAST_COND' : '',
				        'REL_GROUP' : '',
				        'REL_STRAT' : '',
				        'REL_IND' : '',
				        'REL_STATUS' : '',
				        'SUBJ_TO_R' : '',
				        'TAXR_CNTRY' : '',
				        'SCHED_IND' : '',
				        'VEND_NAME' : '',
				        'CURRENCY_ISO' : '',
				        'EXCH_RATE_CM' : '',
				        'HOLD' : ''}]},
				    'PO_ITEMS' : 
				      {'item' : [
				        {'PO_NUMBER' : '',
				        'PO_ITEM' : '',
				        'ADDRESS' : '',
				        'MATERIAL' : '',
				        'PUR_MAT' : '',
				        'INFO_REC' : '',
				        'ITEM_CAT' : '',
				        'ACCTASSCAT' : '',
				        'AGREEMENT' : '',
				        'AGMT_ITEM' : '',
				        'STORE_LOC' : '',
				        'MAT_GRP' : '',
				        'SHORT_TEXT' : '',
				        'DISTRIB' : '',
				        'PART_INV' : '',
				        'KANBAN_IND' : '',
				        'PLANT' : '',
				        'ALLOC_TBL' : '',
				        'AT_ITEM' : '',
				        'UNIT' : '',
				        'NET_PRICE' : '',
				        'PRICE_UNIT' : '',
				        'CONV_NUM1' : '',
				        'CONV_DEN1' : '',
				        'ORDERPR_UN' : '',
				        'PCKG_NO' : '',
				        'PROMOTION' : '',
				        'ACKN_REQD' : '',
				        'TRACKINGNO' : '',
				        'PLAN_DEL' : '',
				        'RET_ITEM' : '',
				        'AT_RELEV' : '',
				        'VEND_MAT' : '',
				        'MANUF_PROF' : '',
				        'MANU_MAT' : '',
				        'MFR_NO' : '',
				        'MFR_NO_EXT' : '',
				        'PO_PRICE' : '',
				        'SHIPPING' : '',
				        'ITEM_CAT_EXT' : '',
				        'PO_UNIT_ISO' : '',
				        'ORDERPR_UN_ISO' : '',
				        'PREQ_NAME' : '',
				        'DISP_QUAN' : '',
				        'QUAL_INSP' : '',
				        'NO_MORE_GR' : '',
				        'DELETE_IND' : '',
				        'NO_ROUNDING' : '',
				        'TAX_CODE' : '',
				        'MATERIAL_EXTERNAL' : '',
				        'MATERIAL_GUID' : '',
				        'MATERIAL_VERSION' : '',
				        'PUR_MAT_EXTERNAL' : '',
				        'PUR_MAT_GUID' : '',
				        'PUR_MAT_VERSION' : '',
				        'VAL_TYPE' : '',
				        'PR_CLOSED' : '',
				        'ACKNOWL_NO' : '',
				        'REQ_SEGMENT' : '',
				        'STK_SEGMENT' : '',
				        'MATERIAL_LONG' : '',
				        'PUR_MAT_LONG' : ''}]}}}}
			}
}